version: '3.8'
services:
  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-boxer
    restart: always
    ports:
      - '443:443'
    volumes:
      - ./sing-box:/etc/sing-box/
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
    logging:
      driver: "none"

