services:
  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./config:/etc/sing-box
      - ./scripts:/scripts
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Moscow  # Moscow time (UTC+3)
    env_file:
      - .env
    entrypoint: ["/bin/bash", "/scripts/entrypoint.sh"]
